# Generated by Django 5.0.4 on 2024-04-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpingHands', '0003_alter_donation_donationname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='deliverypic',
            field=models.ImageField(null=True, upload_to='deliverypic'),
        ),
    ]
