# Generated by Django 5.0.4 on 2024-04-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpingHands', '0004_alter_gallery_deliverypic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='deliverypic',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
